<?php
$categoriesServices = array('automotive' => 'Automotive',
'beauty' => 'Beauty',
'computer' => 'Computer',
'creative' => 'Creative',
'cycle' => 'Cycle',
'event' => 'Event',
'farm_garden' => 'Farm+garden',
'financial' => 'Financial',
'household' => 'Household',
'labor_move' => 'Labor/Move',
'legal' => 'Legal',
'lessons' => 'Lessons',
'massage' => 'Massage',
'marine' => 'Marine',
'pet' => 'Pet',
'real_estate' => 'Real Estate',
'skill_d_trade' => 'Skill\'d trade',
'sm_biz_ads' => 'Sm biz ads',
'therapeutic' => 'Therapeutic',
'travel_vac' => 'Travel/vac',
'write_ed_tr8' => 'Write/ed/tr8');