<?php
define('MODULE_SETTINGS', 1);
define('MODULE_LAWYER', 2);
define('COOKIE_FILE_PATH', SITEDIR.'/cache');

define('BUSINESS_PAYPAL_EMAIL', 'renu09@live.com');
//define('PAYPAL_URL', 'https://www.sandbox.paypal.com/cgi-bin/webscr');
define('PAYPAL_URL', 'https://www.paypal.com/cgi-bin/webscr');

//types of payment
define('PAYMENT_TYPE_CITY', 1);
define('CITY_RATE', 99.99);
define('CITY_ITEM_NUMBER', 1211);
define('SUBSCRIPTION_DURATION', 1);
define('SUBSCRIPTION_UNITS_OF_DURATION', 'M');

define('PAYMENT_TYPE_FOREX', 2);
define('FOREX_RATE', 10.00);
define('FOREX_ITEM_NAME', 'Forex Software');
define('FOREX_ITEM_NUMBER', 1212);
define('FOREX_SUBSCRIPTION_DURATION', 1);
define('FOREX_SUBSCRIPTION_UNITS_OF_DURATION', 'W');

define('PAYMENT_MEMBERSHIP', 3);
define('MEMBERSHIP_RATE', 10.00);
define('MEMBERSHIP_ITEM_NAME', 'Yearly Membership');
define('MEMBERSHIP_ITEM_NUMBER', 1213);
define('MEMBERSHIP_SUBSCRIPTION_DURATION', 1);
define('MEMBERSHIP_SUBSCRIPTION_UNITS_OF_DURATION', 'Y');

$therapies = array(
  array('therapy' => 'Allopathy', 'description' => ''),
  array('therapy' => 'Acupressure', 'description' => 'Similar to acupuncture, but using finger pressure rather than fine needles on specific points along the body to treat ailments such as tension and stress, aches and pains, menstrual cramps, arthritis.'),
  array('therapy' => 'Acupuncture', 'description' => 'Fine needles are inserted at specific points to stimulate, disperse, and regulate the flow of vital energy, and restore a healthy energy balance. In addition to pain relief, acupuncture is also used to improve well being and treat acute, chronic, and degenerative conditions in children and adults.'),
  array('therapy' => 'Aromatherapy', 'description' => 'Using \'essential oils\' distilled from plants, aromatherapy treats emotional disorders such as stress and anxiety as well as a wide range of other ailments. Oils are massaged into the skin in diluted form, inhaled, or placed in baths. Aromatherapy is often used in conjunction with massage therapy, acupuncture, reflexology, herbology, chiropractic, and other holistic treatments.'),
  array('therapy' => 'Astrology', 'description' => 'Astrology is a humanistic attempt at trying to understand the cycles that we share with the forces in the Universe. The planets have corresponding rulership to certain vitamins, minerals, cell salts, herbs, metals, colors and parts of the body. Through the chart, one can look to see what natal health conditions exist. Through these precepts, we can then look at the present and into the future to see what areas of our lives are being affected and potentially how we can head off ill health and promote wellness.'),
  array('therapy' => 'Atlas Orthogonal', 'description' => 'Atlas Orthogonal is a chiropractic program to evaluate and correct subluxation based on scientific and biomechanical procedures. By incorporating the latest advancements in scientific technology, chiropractors can calculate, in precise detail, the vectors specific to an individual subluxation pattern, and program their instrument with the specific correction vectors to deliver the adjustment without any manipulation at all.'),
  array('therapy' => 'Ayurvedic Medicine', 'description' => 'Practiced in India for more than 5,000 years, ayurvedic tradition holds that illness is a state of imbalance among the body\'s systems that can be detected through such diagnostic procedures as reading the pulse and observing the tongue. Nutrition counseling, massage, natural medications, meditation, and other modalities are used to address a broad spectrum of ailments.'),
  array('therapy' => 'Auricular Therapy', 'description' => 'Ancient Egyptian writings state that pain can be relieved by stimulating certain points on the ear. In the 1800\'s, several publications indicated that there were several techniques of cauterization and manipulation of the ears to aid certain disorders. Many benefits can be achieved by massaging and palpating specific points on the ear.'),
  array('therapy' => 'Alexander Technique', 'description' => 'The Alexander Technique is a method that works to change (movement) habits in our everyday activities. It is a simple and practical method for improving ease and freedom of movement, balance, support and coordination. The technique teaches the use of the appropriate amount of effort for a particular activity, giving you more energy for all your activities. It is not a series of treatments or exercises, but rather a reeducation of the mind and body.'),
  array('therapy' => 'Autogenic Training', 'description' => 'It is a century-old European method for achieving relaxation based upon passive concentration and body awareness of specific sensations. Its effectiveness has been shown in relieving many stress-related disorders including anxiety, tension, insomnia, and examination stress. Persons with chronic medical conditions ranging from migraine, colitis, irritable bowel syndrome, diabetes, high blood pressure, to thyroid disease and many other conditions have also been shown to benefit from the practice of autogenic training.'),
  array('therapy' => 'Anthroposophical Medicine', 'description' => 'Anthroposophical Medicine involves an internationally organized group of people who think that Rudolf Steiner (an Austrian physician, 1861-1925) found the ultimate truth - the anthroposophy. Steiner said: By anthroposophy, I mean a scientific investigation of the spiritual world which will bring to light the weaknessess and half-truths not only of science but also of modern mysticism. It is a method which, before attempting to investigate the spiritual worlds, first develops psychic powers not normally used in daily life or in current scientific research.'),
  array('therapy' => 'Auto-Urine Therapy', 'description' => 'This practice comes from Yoga and is the use of one\'s own urine as food, medicine, restorative, transforming agent and immune system booster. It is sometimes called \'Your Own Doctor\'.'),
  array('therapy' => 'Holotropic Breathwork', 'description' => 'It is a simple yet powerful technique for self-exploration and healing, based on combined insights from modern consciousness research, depth psychology and perennial spiritual practices. The method activates non-ordinary states of consciousness which mobilize the spontaneous healing potential of the psyche. Sustained effective breathing, evocative music, focussed energy work and mandala drawing are components of this subjective journey. \'Holotropic\' literally means \'moving towards wholeness\'.'),
  array('therapy' => 'Biofeedback', 'description' => 'A method of monitoring minute metabolic changes in one\'s own body with the aid of sensitive machines. The technique is used especially for stress-related conditions such as asthma, migraines, insomnia, and high blood pressure. Clients learn to make subtle adjustments to move toward a more balanced internal state by consciously visualizing, relaxing, or imagining while observing light, sound, or metered feedback.'),
  array('therapy' => 'Bach Flower Remedies', 'description' => 'A system of herbal remedies devised by Edward Bach, these floral remedies can supposedly alter the disharmonies of personality and emotional state that trouble us all from time to time. These remedies are mostly aimed at curing emotional states rather than physical ones.'),
  array('therapy' => 'Cellular Therapy ', 'description' => 'Cellular therapy also called live cell therapy, cellular suspensions, glandular therapy, fresh cell therapy, siccacell therapy, embryonic cell therapy, and organotherapy -- refers to various procedures in which processed tissue from animal embryos, foetuses or organs, is injected or taken orally. Products are obtained from specific organs or tissues said to correspond with the unhealthy organs or tissues of the recipient. Proponents claim that the recipient\'s body automatically transports the injected cells to the target organs, where they supposedly strengthen them and regenerate their structure. The organs and glands used in cell treatment include brain, pituitary, thyroid, adrenals, thymus, liver, kidney, pancreas, spleen, heart, ovary, testis, and parotid. Several different types of cell or cell extract can be given simultaneously -- some practitioners routinely give up to 20 or more at once.'),
  array('therapy' => 'Chromotherapay or Colour Therapy', 'description' => 'The use of colour ( usually in the form of coloured light) to produce beneficial or healing effects.'),
  array('therapy' => 'Colon Therapy', 'description' => 'The therapeutic goals of colon therapy are to balance body chemistry, eliminate waste, and restore proper tissue and organ function. Colon therapy releases toxins, cleans the blood, stimulates the immune system, and aids in restoring the pH balance in the body. Colon Therapy, also known as colonics, is believed to relieve a wide range of symptoms related to colon dysfunction.'),
  array('therapy' => 'Chelation Therapy', 'description' => 'Chelation therapy is a series of intravenous injections of the synthetic amino acid EDTA, designed to detoxify the body. It is also often used to treat arteriosclerosis. Most frequently, this is administered in an osteopathic or medical doctor\'s office.'),
  array('therapy' => 'Chinese (Oriental) Medicine', 'description' => 'Oriental medical practitioners are trained to use a variety of ancient and modern therapeutic methods - including acupuncture, herbal medicine, massage, heat therapy, and nutritional and lifestyle counseling - to treat a broad range of both chronic and acute illnesses.'),
  array('therapy' => 'Chiropractic', 'description' => 'The chiropractic views the spine as the backbone of human health: misalignments of the vertebrae caused by poor posture or trauma cause pressure on the spinal nerve roots, leading to diminished function and illness. Through manipulation or adjustment of the spine, treatment seeks to analyze and correct these misalignments.'),
  array('therapy' => 'Colonics', 'description' => 'A colonic is a colon irrigation, the irrigation of the large intestine with sanitized, filtered water under gentle pressure to wash out or detoxify it of stagnated fecal material; it is a full intestinal enema.'),
  array('therapy' => 'Counseling/Psychotherapy', 'description' => 'This broad category covers a range of practitioners, from career counselors to psychotherapies who treat depression, stress, addiction, and emotional issues. Formats can vary from individual counseling to group therapy. Some therapists may also incorporate bodywork, ritual, energy healing, and other alternative modalities as part of their practice.'),
  array('therapy' => 'Cupping', 'description' => 'It is a traditional Chinese medical technique which applies suction to diseased parts of the body using ceramic glass or bamboo cups in order to increase the regional circulation and thereby promote healing. In very ancient times the  horns of animals were used for this purpose.'),
  array('therapy' => 'Craniosacral Therapy', 'description' => 'This is a manual therapeutic procedure for remedying distortions in the structure and function of the craniosacral mechanism - the brain and spinal cord, the bones of the skull, the sacrum, and interconnected membranes. It is used to treat chronic pain, migraine headaches, TMJ, and a range of other conditions.'),
  array('therapy' => 'Dance/Movement Therapies', 'description' => 'Dance and/or movement therapy uses expressive movement as a therapeutic tool for both personal expression and psychological or emotional healing. Practitioners work with people with physical disabilities, addition issues, sexual abuse histories, eating disorders, and other concerns.'),
  array('therapy' => 'Dentistry, Holistic', 'description' => 'Holistic dentists are licensed dentists who bring an interdisciplinary approach to their practice. They may incorporate such methods as homeopathy, nutrition and acupuncture into their treatment plans. Most holistic dentists emphasize wellness and preventive care while avoiding silver-mercury fillings.'),
  array('therapy' => 'Dowsing', 'description' => 'Dowsing is an ancient art of searching for hidden things (water, precious metals, etc) using one of the senses that many of us are not even aware of possessing; reportedly 80% of people have this special gift - an ability to sense things not perceptible to others. Some of these people do not need any extra tools to do that - they just KNOW where is the best place to dig a well or where the gold treasure is hidden.'),
  array('therapy' => 'Ear Candling', 'description' => 'Primarily used for wax buildup and related hearing problems, ear candling is also used for ear infections and sinus infections. Treatment involves placing the narrow end of a specially designed hollow candle at the entry of the ear canal, while the opposite end is lit.'),
  array('therapy' => 'Electropathy ', 'description' => 'Electropathy is a specialised system of therapeutics which involves the use of various forms of electric currents for medicinal purposes.'),
  array('therapy' => 'Fasting Therapy ', 'description' => 'Therapeutic fasting or fasting for health is a purifying and rejuvenating process by which toxic waste matters of the body are eliminated and regeneration of diseased tissues occurs.'),
  array('therapy' => 'Feng Shui', 'description' => 'Ancient Chinese practice of arranging the home or work environment to promote health, happiness, and prosperity. Consultants may recommend changes in the surroundings - from color selection to furniture placement - in order to promote a health flow of chi, or vital energy.'),
  array('therapy' => 'Feldenkrais Method', 'description' => 'The Feldenkrais Method is a systematic approach to neuromuscular relearning. The method is suited to healthy people who want to increase the flexibility of their bodies and thinking, people with neurological and movement disorders, and those who want to achieve excellence in the arts, sports, or any endeavor.'),
  array('therapy' => 'Flower Essences', 'description' => 'A method of alleviating negative emotional states that may contribute to illness or hinder personal growth. Drops of a solution infused with the captured \'essence\' of a flower are placed under the tongue or in a beverage. The practitioner helps the client choose appropriate essences, focusing on the client\'s emotional state rather than on a particular physical condition.'),
  array('therapy' => 'Gem Therapy', 'description' => 'A relatively recent discovery in the field of alternative medicines, it involves the use of specific gems to treat specific ailments.'),
  array('therapy' => 'Herbalism', 'description' => 'An ancient form of healing still widely used in much of the world, herbalism uses natural plants or plant-based substances to treat a range of illnesses and to enhance the functioning of the body\'s systems. Though herbalism is not a licensed professional modality in the United States, herbs are \'prescribed\' by a range of practitioners. '),
  array('therapy' => 'Heliotherapy', 'description' => 'Heliotherapy is the science conducted on the positive effects of the sun and is an effective tool in boosting the body\'s immune system.'),
  array('therapy' => 'Holistic Medicine', 'description' => 'A descriptive term for a healing philosophy that views a patient as a whole person, not as just a disease or a collection of symptoms. In the course of treatment, holistic medical practitioners may address a client\'s emotional and spiritual dimensions as well as the nutritional, environmental, and lifestyle factors that may contribute to an illness. Many holistic medical practitioners combine conventional forms of treatment with natural or alternative treatments. '),
  array('therapy' => 'Homoeopathy', 'description' => 'A medical system that uses infinitesimal doses of natural substances - called remedies - to stimulate a person\'s immune and defense system. A remedy is individually chosen for a sick person based on its capacity to cause, if given in overdose, physical and psychological symptoms similar to those a patient is experiencing. Common conditions hoeopathy addresses are infant and childhood diseases, infections, fatigue, allergies, and chronic illnesses such as arthritis.'),
  array('therapy' => 'Hypnotherapy', 'description' => 'A means of bypassing the conscious mind and accessing the subconscious, where suppressed memories, repressed emotions, and forgotten events may remain recorded. Hypnosis may facilitate behavioral, emotional, or attitudinal change such as weight loss, or smoking cessation.It is also used to treat phobias, stress, and as an adjunct in the treatment of illness.'),
  array('therapy' => 'Hydrotherapy', 'description' => 'It is defined as the scientific application of water for therapeutic purposes. Water may be used at various temperatures, in different modes and in different forms.'),
  array('therapy' => 'Iridology', 'description' => 'The diagnostic system based on the premise that every organ has a corresponding location within the iris of the eye, which can serve as an indicator of the individual organ\'s health or disease. Iridology is used by naturopaths and other practitioners, particularly when diagnosis achieved through standard methods is unclear.'),
  array('therapy' => 'Kinesiology', 'description' => 'Kinesiology is the study of the human body during movement. There are many disciplines within Kinesiology including anatomy, biomechanics, exercise physiology, motor control, motor learning, neuromuscular physiology, sports psychology, and philosophy. Kinesiology graduates enter a variety of careers and graduate programs related to the understanding of how the body works including medical school, physical and occupational therapy schools, athletic training, and other health professions, public school teaching, sport and exercise related fields, the military, business, and law.'),
  array('therapy' => 'Lymph Drainage Therapy', 'description' => 'Therapy to drain and improve the lymphatic vessels, a system of tubes or canals through which lymph is carried from different parts of the body.'),
  array('therapy' => 'MassageTherapeutic', 'description' => 'A general term for a range of therapeutic approaches with roots in both Eastern and Western cultures. It involves the practice of manipulating a person\'s muscles and other soft tissue with the intent of improving a person\'s well-being or health, and may include, but not be limited to, effleurage, deep tissue, percussion, vibration, and joint movement.'),
  array('therapy' => 'Magnetotherapy ', 'description' => 'The art of healing by the application of natural and artificial magnets to the diseased parts of the human body. It is a clinical system by which human ailments are treated and cured through the application of magnets to the body of the patients. '),
  array('therapy' => 'Midwifery/Childbirth Support', 'description' => 'Midwives provide education and support during pregnancy, assist the mother during labor and delivery, and provide follow-up care. Practitioners of childbirth support include childbirth educators, assistants, and doulas (women labor coaches who also provide postpartum home care). '),
  array('therapy' => 'Native American Herbology', 'description' => 'Native American healers and spiritual leaders seldom travel far from their homes and even more infrequently publicize their work - it is not the way. However, there is a body of knowledge about the herbal treatments used by various Native People. Much of the information has been tested and incorporated into our present herbal therapies.'),
  array('therapy' => 'Natural Products', 'description' => 'Products composed of organically grown plants and containing no chemicals. These products may be used cosmetically as well as for health and nutrition. '),
  array('therapy' => 'Naturopathic Medicine', 'description' => 'Naturopathic physicians work to restore and support the body\'s own healing abilities using a variety of modalities including nutrition, herbal medicine, homeopathic medicine, and orient medicine. A primary health-care system which emphasizes the curative power of nature, treating both acute and chronic illnesses in all age groups.'),
  array('therapy' => 'Network Chiropractic', 'description' => 'This refers to a network of independent chiropractic offices that use Network Spinal Analysis, a method characterized by the sequential application of a number of gentle, specific adjusting techniques. Care progresses through a series of levels that parallel spinal and quality-of-life changes.'),
  array('therapy' => 'Ohashiatsu', 'description' => 'A system of physical techniques, exercise and meditation used to relieve tension and fatigue and induce a state of harmony and peace. The practitioner first assesses a person\'s state by feeling the hara, the area below the navel. Then, using continuous and flowing movements, the practitioner presses and stretches the body\'s energy channels, working in unison with the person\'s breathing.'),
  array('therapy' => 'Oriental Diagnosis', 'description' => 'It is a dignostic procedure by which the patient\'s pulse is examined to detect disease according to traditional Chinese medicine.'),
  array('therapy' => 'Osteopathic Medicine', 'description' => 'Osteopathic physicians provide comprehensive medical care, including preventive medicine, diagnosis, surgery, prescription medications, and hospital referrals. In diagnosis and treatment, they pay particular attention to the joints, bones, muscles, and nerves and are specially trained in osteopathic manipulative treatment - using their hands to diagnose, treat, and prevent illness.'),
  array('therapy' => 'Physiotherapy', 'description' => 'It is a wonderful manipulative technique by which the deformities of an individual are modified in order to notify the body and the vital organs in accordance with the principles of naturopathy.'),
  array('therapy' => 'Pyramid Healing', 'description' => 'A potential healing method using pyramidal structures.'),
  array('therapy' => 'Radiesthesia', 'description' => 'The use of of dowsing or divining to diagnose disease and select remedies. It can be used to diagnose any condition according to leading practitioners. Basically, it is simply a method of arriving at a diagnosis and treatment using the human being as the diagnostic instrument. '),
  array('therapy' => 'Radionics', 'description' => 'A therapy that has grown up around the ability of the human being to use radiesthesia together with simple instruments to help in the diagnosis of disease in animals, plants and humans and then to treat this disease at a distance without the presence of the patient. '),
  array('therapy' => 'Reconstructive Therapy/Prolotherapy', 'description' => 'Reconstructive therapy uses injections of natural substances such as dextrose, glycerin, and phenol in order to stimulate the growth of connective tissue and this strengthens weak or damaged joints, cartilage, ligaments, and tendons. This therapy is used to treat degenerative arthritis, lower back pain, torn ligaments and cartilage, carpal tunnel syndrome, and other conditions.'),
  array('therapy' => 'Reflexology', 'description' => 'This modality is based on the idea that specific points on the feet and hands correspond with organs and tissues throughout the body. With fingers and thumbs, the practitioner applies pressure to these points to treat a wide range of stress-related illnesses.'),
  array('therapy' => 'Reiki', 'description' => 'Practitioners of this ancient Tibetan healing system use light hand placements to channel healing energies to the recipient. While practitioners may vary widely in technique and philosophy, Reiki is commonly used to treat emotional and mental distress as well as chronic and acute physical problems, and to assist the recipient in achieving spiritual focus and clarity.'),
  array('therapy' => 'Rolfing', 'description' => 'A massage technique using deep manipulation of the fascia (connective tissue) to restore the body\'s natural alignment, which may have become rigid through injury, emotional trauma, and inefficient movement habits. The process involves ten sessions, each focusing on a different part of the body.'),
  array('therapy' => 'Shiatsu', 'description' => 'The most widely known form of accupressure, shiatsu has been used in Japan for more than 1,000 years to treat pain and illness and for general health maintenance. Using a series of techniques, practitioners apply rhythmic finger pressure at specific points on the body in order to stimulate chi, or the vital energy.'),
  array('therapy' => 'Sound Therapy ', 'description' => 'The use of sound waves to heal.'),
  array('therapy' => 'Tibetan Medicine', 'description' => 'Evolved as a systhesis of Tibetan, Chinese and Persian Medicine, and even Ayurveda. These remedies include indigenous herbs, fruits, flowers, metallic powders and minerals given in tablets, and are especially effected in treating rheumatism, asthma, gastritis, diabetes and many neurological disorders.'),
  array('therapy' => 'Unani', 'description' => 'Involves the use of plants and herbs, these remedies are known to provide cures for diseases such as sinusitus , leucoderma, rheumatism, jaundice and elephantiasis.'),
  array('therapy' => 'Vision Therapies', 'description' => 'Through exercise and relaxation techniques, vision may actually be improved to the point that glasses may no longer be needed. Therapies are typically offered by licensed optometrists and ophthalmologists.'),
  array('therapy' => 'Vitamin Therapy', 'description' => 'A complementary therapy of vitamin usage combined with other treatments to address a range of illnesses and to enhance the functioning of the body\'s systems. Assists the immune system in combating diseases such as Chronic Fatigue Syndrome and HIV/AIDS.'),
  array('therapy' => 'Wellness Restoration', 'description' => 'A comprehensive program designed to increase muscle mass by using adequate nutrition, supplementation, anabolic steroid therapy and resistance weight training to prevent/reverse wasting in HIV disease.'),
  array('therapy' => 'Yoga Therapy', 'description' => 'The use of yoga to address mental and physical problems while integrating body and mind.')
);